name: Release DevOps with Docker # Name of the workflow

# On a push to the branch named master
on:
  push:
    branches:
      - main

# Job called build runs-on ubuntu-latest
jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
        # Checkout to the repository
        - name: Checkout
          uses: actions/checkout@v2

        # Check if secrets are set
        - name: Check if secrets are set
          run: echo "GH_USERNAME=${{ secrets.GH_USERNAME }}" && echo "DOCKERHUB_TOKEN=${{ secrets.DOCKERHUB_TOKEN }}"


        # Login to Docker Hub
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.GH_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        # Builds devopsdockeruh/docker-hy.github.io
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: devopsdockeruh/coursepage:latest